/**
 * Created by Administrator on 2017/5/9 0009.
 */
export const CHANGE_NAME = 'CHANGE_NAME'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const CHANGE_MESSAGE_STATUS = 'CHANGE_MESSAGE_STATUS'
export const MESSAGE_DETAIL = 'MESSAGE_DETAIL'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CHANGE_FOOTER_STATE = 'CHANGE_FOOTER_STATE'
